services:
  - type: web           # Web service
    name: melodify-backend
    env: docker         # Use Docker environment
    plan: free
    autoDeploy: true    # Auto-deploy on GitHub push
    branch: main        # Deploy from main branch
    rootDir: Melodify-Backend # Path to backend folder
    envVars:
      - key: YOUTUBE_API_KEY
        fromDotEnv: true      # Pull from .env, or set manually in dashboard