services:
  - type: web
    name: melodify-backend
    env: node
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y yt-dlp && \
      npm install
    startCommand: node server.js
    envVars:
      - key: YOUTUBE_API_KEY
        value: 
    rootDir: Melodify-Backend